// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  before_after: dynamic(() => import("./BeforeAfter")),
  hero: dynamic(() => import("./Hero")),
  image_group: dynamic(() => import("./ImageGroup")),
  image_left: dynamic(() => import("./ImageWithTextonOneSide")),
  rich_text: dynamic(() => import("./RichText")),
  single_image: dynamic(() => import("./SingleImage")),
  text_block: dynamic(() => import("./TextBlock")),
};
